// The 52 sports under ISN's programmes — the selectable universe for the
// screening-import sport field (searchable datalist). Placeholder roster
// assembled from the seeded sports plus Malaysia's major games-programme
// sports; swap entries here when ISN's official list is confirmed. Sports
// with curated alert regions live in lib/screeningAlerts.ts — unmapped
// sports still get the High-threshold safety net.
export const ISN_SPORTS: string[] = [
  'Archery',
  'Artistic Swimming',
  'Athletics',
  'Badminton',
  'Baseball',
  'Basketball',
  'Beach Volleyball',
  'Bodybuilding',
  'Bowling',
  'Bowls',
  'Boxing',
  'Canoeing',
  'Cricket',
  'Cycling',
  'Dancesport',
  'Diving',
  'Equestrian',
  'E-sports',
  'Fencing',
  'Football',
  'Futsal',
  'Golf',
  'Gymnastics',
  'Handball',
  'Hockey',
  'Ice Skating',
  'Judo',
  'Karate',
  'Kayaking',
  'Muay Thai',
  'Netball',
  'Pencak Silat',
  'Petanque',
  'Rowing',
  'Rugby',
  'Sailing',
  'Sepak Takraw',
  'Shooting',
  'Silat',
  'Softball',
  'Sport Climbing',
  'Squash',
  'Surfing',
  'Swimming',
  'Table Tennis',
  'Taekwondo',
  'Tennis',
  'Triathlon',
  'Volleyball',
  'Water Polo',
  'Weightlifting',
  'Wushu',
];
